# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_place_order_request import SodacardsDevpublicV1PlaceOrderRequest

class TestSodacardsDevpublicV1PlaceOrderRequest(unittest.TestCase):
    """SodacardsDevpublicV1PlaceOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1PlaceOrderRequest:
        """Test SodacardsDevpublicV1PlaceOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1PlaceOrderRequest`
        """
        model = SodacardsDevpublicV1PlaceOrderRequest()
        if include_optional:
            return SodacardsDevpublicV1PlaceOrderRequest(
                lines = [
                    sodacards.models.order_line.OrderLine(
                        product_id = '', 
                        quantity = 56, 
                        input_fields = {
                            'key' : ''
                            }, )
                    ],
                reference = ''
            )
        else:
            return SodacardsDevpublicV1PlaceOrderRequest(
        )
        """

    def testSodacardsDevpublicV1PlaceOrderRequest(self):
        """Test SodacardsDevpublicV1PlaceOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
