# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_placed_order import SodacardsDevpublicV1PlacedOrder

class TestSodacardsDevpublicV1PlacedOrder(unittest.TestCase):
    """SodacardsDevpublicV1PlacedOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1PlacedOrder:
        """Test SodacardsDevpublicV1PlacedOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1PlacedOrder`
        """
        model = SodacardsDevpublicV1PlacedOrder()
        if include_optional:
            return SodacardsDevpublicV1PlacedOrder(
                id = '',
                status = '',
                total = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', )
            )
        else:
            return SodacardsDevpublicV1PlacedOrder(
        )
        """

    def testSodacardsDevpublicV1PlacedOrder(self):
        """Test SodacardsDevpublicV1PlacedOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
