# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_list_catalog_response import SodacardsDevpublicV1ListCatalogResponse

class TestSodacardsDevpublicV1ListCatalogResponse(unittest.TestCase):
    """SodacardsDevpublicV1ListCatalogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1ListCatalogResponse:
        """Test SodacardsDevpublicV1ListCatalogResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1ListCatalogResponse`
        """
        model = SodacardsDevpublicV1ListCatalogResponse()
        if include_optional:
            return SodacardsDevpublicV1ListCatalogResponse(
                data = [
                    sodacards.models.product.Product(
                        id = '', 
                        name = '', 
                        face_value = null, 
                        price = null, 
                        strike_price = null, 
                        bonus = '', 
                        min_quantity = 56, 
                        max_quantity = 56, 
                        purchasable = True, )
                    ],
                has_more = True,
                next_cursor = ''
            )
        else:
            return SodacardsDevpublicV1ListCatalogResponse(
        )
        """

    def testSodacardsDevpublicV1ListCatalogResponse(self):
        """Test SodacardsDevpublicV1ListCatalogResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
