# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_get_product_response import SodacardsDevpublicV1GetProductResponse

class TestSodacardsDevpublicV1GetProductResponse(unittest.TestCase):
    """SodacardsDevpublicV1GetProductResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1GetProductResponse:
        """Test SodacardsDevpublicV1GetProductResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1GetProductResponse`
        """
        model = SodacardsDevpublicV1GetProductResponse()
        if include_optional:
            return SodacardsDevpublicV1GetProductResponse(
                product = sodacards.models.product.Product(
                    id = '', 
                    name = '', 
                    face_value = null, 
                    price = null, 
                    strike_price = null, 
                    bonus = '', 
                    min_quantity = 56, 
                    max_quantity = 56, 
                    purchasable = True, 
                    input_fields = [
                        sodacards.models.input_field_spec.InputFieldSpec(
                            key = '', 
                            type = '', 
                            required = True, 
                            regex = '', 
                            options = [
                                sodacards.models.input_field_option.InputFieldOption(
                                    value = '', 
                                    label = '', 
                                    parent_value = '', )
                                ], )
                        ], )
            )
        else:
            return SodacardsDevpublicV1GetProductResponse(
        )
        """

    def testSodacardsDevpublicV1GetProductResponse(self):
        """Test SodacardsDevpublicV1GetProductResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
