# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_list_webhooks_response import SodacardsDevpublicV1ListWebhooksResponse

class TestSodacardsDevpublicV1ListWebhooksResponse(unittest.TestCase):
    """SodacardsDevpublicV1ListWebhooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1ListWebhooksResponse:
        """Test SodacardsDevpublicV1ListWebhooksResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1ListWebhooksResponse`
        """
        model = SodacardsDevpublicV1ListWebhooksResponse()
        if include_optional:
            return SodacardsDevpublicV1ListWebhooksResponse(
                webhooks = [
                    sodacards.models.webhook.Webhook(
                        id = '', 
                        url = '', 
                        events = [
                            ''
                            ], 
                        active = True, 
                        created_at = '', )
                    ]
            )
        else:
            return SodacardsDevpublicV1ListWebhooksResponse(
        )
        """

    def testSodacardsDevpublicV1ListWebhooksResponse(self):
        """Test SodacardsDevpublicV1ListWebhooksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
