# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_order_item import SodacardsDevpublicV1OrderItem

class TestSodacardsDevpublicV1OrderItem(unittest.TestCase):
    """SodacardsDevpublicV1OrderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1OrderItem:
        """Test SodacardsDevpublicV1OrderItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1OrderItem`
        """
        model = SodacardsDevpublicV1OrderItem()
        if include_optional:
            return SodacardsDevpublicV1OrderItem(
                product_id = '',
                name = '',
                unit_price = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', ),
                quantity = 56,
                line_total = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', ),
                input_fields = {
                    'key' : ''
                    }
            )
        else:
            return SodacardsDevpublicV1OrderItem(
        )
        """

    def testSodacardsDevpublicV1OrderItem(self):
        """Test SodacardsDevpublicV1OrderItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
