# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.api.public_api_service_api import PublicAPIServiceApi


class TestPublicAPIServiceApi(unittest.TestCase):
    """PublicAPIServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicAPIServiceApi()

    def tearDown(self) -> None:
        pass

    def test_public_api_service_get_balance(self) -> None:
        """Test case for public_api_service_get_balance

        GetBalance
        """
        pass


if __name__ == '__main__':
    unittest.main()
