# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_register_webhook_response import SodacardsDevpublicV1RegisterWebhookResponse

class TestSodacardsDevpublicV1RegisterWebhookResponse(unittest.TestCase):
    """SodacardsDevpublicV1RegisterWebhookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1RegisterWebhookResponse:
        """Test SodacardsDevpublicV1RegisterWebhookResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1RegisterWebhookResponse`
        """
        model = SodacardsDevpublicV1RegisterWebhookResponse()
        if include_optional:
            return SodacardsDevpublicV1RegisterWebhookResponse(
                webhook = sodacards.models.webhook.Webhook(
                    id = '', 
                    url = '', 
                    events = [
                        ''
                        ], 
                    active = True, 
                    created_at = '', ),
                secret = ''
            )
        else:
            return SodacardsDevpublicV1RegisterWebhookResponse(
        )
        """

    def testSodacardsDevpublicV1RegisterWebhookResponse(self):
        """Test SodacardsDevpublicV1RegisterWebhookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
