# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        DeleteWebhook
        """
        pass

    def test_get_order(self) -> None:
        """Test case for get_order

        GetOrder
        """
        pass

    def test_get_product(self) -> None:
        """Test case for get_product

        GetProduct
        """
        pass

    def test_list_catalog(self) -> None:
        """Test case for list_catalog

        ListCatalog
        """
        pass

    def test_list_orders(self) -> None:
        """Test case for list_orders

        ListOrders
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        ListWebhooks
        """
        pass

    def test_ping(self) -> None:
        """Test case for ping

        Ping
        """
        pass

    def test_place_order(self) -> None:
        """Test case for place_order

        PlaceOrder
        """
        pass

    def test_register_webhook(self) -> None:
        """Test case for register_webhook

        RegisterWebhook
        """
        pass

    def test_reveal_order_codes(self) -> None:
        """Test case for reveal_order_codes

        RevealOrderCodes
        """
        pass


if __name__ == '__main__':
    unittest.main()
