# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_get_balance_response import SodacardsDevpublicV1GetBalanceResponse

class TestSodacardsDevpublicV1GetBalanceResponse(unittest.TestCase):
    """SodacardsDevpublicV1GetBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1GetBalanceResponse:
        """Test SodacardsDevpublicV1GetBalanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1GetBalanceResponse`
        """
        model = SodacardsDevpublicV1GetBalanceResponse()
        if include_optional:
            return SodacardsDevpublicV1GetBalanceResponse(
                balance = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', 
                    minor_unit_exponent = 56, )
            )
        else:
            return SodacardsDevpublicV1GetBalanceResponse(
        )
        """

    def testSodacardsDevpublicV1GetBalanceResponse(self):
        """Test SodacardsDevpublicV1GetBalanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
