# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_product import SodacardsDevpublicV1Product

class TestSodacardsDevpublicV1Product(unittest.TestCase):
    """SodacardsDevpublicV1Product unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1Product:
        """Test SodacardsDevpublicV1Product
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1Product`
        """
        model = SodacardsDevpublicV1Product()
        if include_optional:
            return SodacardsDevpublicV1Product(
                id = '',
                name = '',
                face_value = sodacards.models.product_face_value.ProductFaceValue(
                    amount = '', 
                    currency = '', ),
                price = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', 
                    minor_unit_exponent = 56, ),
                strike_price = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', 
                    minor_unit_exponent = 56, ),
                bonus = '',
                min_quantity = 56,
                max_quantity = 56,
                purchasable = True,
                input_fields = [
                    sodacards.models.input_field_spec.InputFieldSpec(
                        key = '', 
                        type = '', 
                        required = True, 
                        regex = '', 
                        options = [
                            sodacards.models.input_field_option.InputFieldOption(
                                value = '', 
                                label = '', 
                                parent_value = '', )
                            ], )
                    ]
            )
        else:
            return SodacardsDevpublicV1Product(
        )
        """

    def testSodacardsDevpublicV1Product(self):
        """Test SodacardsDevpublicV1Product"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
