# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_list_orders_request import SodacardsDevpublicV1ListOrdersRequest

class TestSodacardsDevpublicV1ListOrdersRequest(unittest.TestCase):
    """SodacardsDevpublicV1ListOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1ListOrdersRequest:
        """Test SodacardsDevpublicV1ListOrdersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1ListOrdersRequest`
        """
        model = SodacardsDevpublicV1ListOrdersRequest()
        if include_optional:
            return SodacardsDevpublicV1ListOrdersRequest(
                limit = 56,
                cursor = '',
                reference = ''
            )
        else:
            return SodacardsDevpublicV1ListOrdersRequest(
        )
        """

    def testSodacardsDevpublicV1ListOrdersRequest(self):
        """Test SodacardsDevpublicV1ListOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
