# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_order import SodacardsDevpublicV1Order

class TestSodacardsDevpublicV1Order(unittest.TestCase):
    """SodacardsDevpublicV1Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1Order:
        """Test SodacardsDevpublicV1Order
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1Order`
        """
        model = SodacardsDevpublicV1Order()
        if include_optional:
            return SodacardsDevpublicV1Order(
                id = '',
                status = '',
                total = sodacards.models.money.Money(
                    amount = 56, 
                    currency = '', ),
                created_at = '',
                reference = '',
                lines = [
                    sodacards.models.order_item.OrderItem(
                        product_id = '', 
                        name = '', 
                        unit_price = null, 
                        quantity = 56, 
                        line_total = null, 
                        input_fields = {
                            'key' : ''
                            }, )
                    ]
            )
        else:
            return SodacardsDevpublicV1Order(
        )
        """

    def testSodacardsDevpublicV1Order(self):
        """Test SodacardsDevpublicV1Order"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
