# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_list_orders_response import SodacardsDevpublicV1ListOrdersResponse

class TestSodacardsDevpublicV1ListOrdersResponse(unittest.TestCase):
    """SodacardsDevpublicV1ListOrdersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1ListOrdersResponse:
        """Test SodacardsDevpublicV1ListOrdersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1ListOrdersResponse`
        """
        model = SodacardsDevpublicV1ListOrdersResponse()
        if include_optional:
            return SodacardsDevpublicV1ListOrdersResponse(
                data = [
                    sodacards.models.order.Order(
                        id = '', 
                        status = '', 
                        total = null, 
                        created_at = '', 
                        reference = '', 
                        lines = [
                            sodacards.models.order_item.OrderItem(
                                product_id = '', 
                                name = '', 
                                unit_price = null, 
                                quantity = 56, 
                                line_total = null, 
                                input_fields = {
                                    'key' : ''
                                    }, )
                            ], )
                    ],
                has_more = True,
                next_cursor = ''
            )
        else:
            return SodacardsDevpublicV1ListOrdersResponse(
        )
        """

    def testSodacardsDevpublicV1ListOrdersResponse(self):
        """Test SodacardsDevpublicV1ListOrdersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
