# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete a webhook endpoint
        """
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        Get wallet balance
        """
        pass

    def test_get_order(self) -> None:
        """Test case for get_order

        Get an order
        """
        pass

    def test_get_product(self) -> None:
        """Test case for get_product

        Get a product
        """
        pass

    def test_list_catalog(self) -> None:
        """Test case for list_catalog

        List catalog products
        """
        pass

    def test_list_orders(self) -> None:
        """Test case for list_orders

        List orders
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List webhook endpoints
        """
        pass

    def test_ping(self) -> None:
        """Test case for ping

        Ping
        """
        pass

    def test_place_order(self) -> None:
        """Test case for place_order

        Place an order
        """
        pass

    def test_register_webhook(self) -> None:
        """Test case for register_webhook

        Register a webhook endpoint
        """
        pass

    def test_reveal_order_codes(self) -> None:
        """Test case for reveal_order_codes

        Reveal order codes
        """
        pass

    def test_rotate_webhook_secret(self) -> None:
        """Test case for rotate_webhook_secret

        Rotate a webhook signing secret
        """
        pass


if __name__ == '__main__':
    unittest.main()
