# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sodacards.models.sodacards_devpublic_v1_get_product_request import SodacardsDevpublicV1GetProductRequest

class TestSodacardsDevpublicV1GetProductRequest(unittest.TestCase):
    """SodacardsDevpublicV1GetProductRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SodacardsDevpublicV1GetProductRequest:
        """Test SodacardsDevpublicV1GetProductRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SodacardsDevpublicV1GetProductRequest`
        """
        model = SodacardsDevpublicV1GetProductRequest()
        if include_optional:
            return SodacardsDevpublicV1GetProductRequest(
                id = ''
            )
        else:
            return SodacardsDevpublicV1GetProductRequest(
        )
        """

    def testSodacardsDevpublicV1GetProductRequest(self):
        """Test SodacardsDevpublicV1GetProductRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
