# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Problem(BaseModel):
    """
    An RFC 9457 problem+json error. Switch on `code`, the stable machine-readable reason; the HTTP status frames the broad category.
    """ # noqa: E501
    type: StrictStr = Field(description="A stable URI identifying the error kind; it resolves to the docs section for that code.")
    title: StrictStr = Field(description="A short, human-readable summary of the error kind.")
    status: StrictInt = Field(description="The HTTP status code, repeated in the body for convenience.")
    code: StrictStr = Field(description="The machine-readable reason (e.g. \"insufficient_balance\"): switch on this, never on the human text.")
    detail: Optional[StrictStr] = Field(default=None, description="A human-readable explanation of this specific occurrence. May be absent.")
    request_id: Optional[StrictStr] = Field(default=None, description="Identifies this request in support conversations. May be absent.")
    __properties: ClassVar[List[str]] = ["type", "title", "status", "code", "detail", "request_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "code": obj.get("code"),
            "detail": obj.get("detail"),
            "request_id": obj.get("request_id")
        })
        return _obj


