# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sodacards.models.sodacards_devpublic_v1_money import SodacardsDevpublicV1Money
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SodacardsDevpublicV1OrderItem(BaseModel):
    """
    OrderItem is one line of an order.
    """ # noqa: E501
    product_id: Optional[StrictStr] = Field(default=None, description="product_id is the product ordered on this line.", alias="productId")
    name: Optional[StrictStr] = Field(default=None, description="name is the product name at order time.")
    unit_price: Optional[SodacardsDevpublicV1Money] = Field(default=None, description="unit_price is the price of one unit, in the currency of Money.", alias="unitPrice")
    quantity: Optional[StrictInt] = Field(default=None, description="quantity is how many units were ordered.")
    line_total: Optional[SodacardsDevpublicV1Money] = Field(default=None, description="line_total is unit_price times quantity, in the currency of Money.", alias="lineTotal")
    input_fields: Optional[Dict[str, StrictStr]] = Field(default=None, description="input_fields are the purchase-form values submitted for this line.", alias="inputFields")
    __properties: ClassVar[List[str]] = ["productId", "name", "unitPrice", "quantity", "lineTotal", "inputFields"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1OrderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of unit_price
        if self.unit_price:
            _dict['unitPrice'] = self.unit_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of line_total
        if self.line_total:
            _dict['lineTotal'] = self.line_total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1OrderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "productId": obj.get("productId"),
            "name": obj.get("name"),
            "unitPrice": SodacardsDevpublicV1Money.from_dict(obj["unitPrice"]) if obj.get("unitPrice") is not None else None,
            "quantity": obj.get("quantity"),
            "lineTotal": SodacardsDevpublicV1Money.from_dict(obj["lineTotal"]) if obj.get("lineTotal") is not None else None,
            "inputFields": obj.get("inputFields")
        })
        return _obj


