# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from sodacards.models.sodacards_devpublic_v1_revealed_code import SodacardsDevpublicV1RevealedCode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SodacardsDevpublicV1RevealOrderCodesResponse(BaseModel):
    """
    SodacardsDevpublicV1RevealOrderCodesResponse
    """ # noqa: E501
    codes: Optional[List[SodacardsDevpublicV1RevealedCode]] = Field(default=None, description="codes are the delivered codes of the order.")
    __properties: ClassVar[List[str]] = ["codes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1RevealOrderCodesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in codes (list)
        _items = []
        if self.codes:
            for _item_codes in self.codes:
                if _item_codes:
                    _items.append(_item_codes.to_dict())
            _dict['codes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1RevealOrderCodesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "codes": [SodacardsDevpublicV1RevealedCode.from_dict(_item) for _item in obj["codes"]] if obj.get("codes") is not None else None
        })
        return _obj


