# coding: utf-8

"""
    SODACARDS Developer API

    Sell gift cards and game top-ups from your own systems.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sodacards.models.sodacards_devpublic_v1_money import SodacardsDevpublicV1Money
from sodacards.models.sodacards_devpublic_v1_product_face_value import SodacardsDevpublicV1ProductFaceValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SodacardsDevpublicV1Product(BaseModel):
    """
    Product is one sellable item in the reseller catalog. Its id is what an order  line references. It never carries the supplier cost or routing.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="id identifies the product; use it to place an order for this item.")
    name: Optional[StrictStr] = Field(default=None, description="name is the human-readable product name.")
    face_value: Optional[SodacardsDevpublicV1ProductFaceValue] = Field(default=None, description="face_value is the nominal value printed on the item (e.g. a 10 USD card),  which may differ from the currency the reseller pays in.", alias="faceValue")
    price: Optional[SodacardsDevpublicV1Money] = Field(default=None, description="price is what the reseller pays, in the currency of Money. It is absent when the item is not  yet priced (listed but not purchasable).")
    strike_price: Optional[SodacardsDevpublicV1Money] = Field(default=None, description="strike_price is an optional reference (pre-discount) price, in the currency of Money, for  display. Absent when there is none.", alias="strikePrice")
    bonus: Optional[StrictStr] = Field(default=None, description="bonus describes any extra value granted with the item, e.g. \"+10%\". Empty  when there is none.")
    min_quantity: Optional[StrictInt] = Field(default=None, description="min_quantity and max_quantity bound how many units an order line may buy.", alias="minQuantity")
    max_quantity: Optional[StrictInt] = Field(default=None, alias="maxQuantity")
    purchasable: Optional[StrictBool] = Field(default=None, description="purchasable is true when the item has a price and can be ordered now.")
    __properties: ClassVar[List[str]] = ["id", "name", "faceValue", "price", "strikePrice", "bonus", "minQuantity", "maxQuantity", "purchasable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1Product from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of face_value
        if self.face_value:
            _dict['faceValue'] = self.face_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of strike_price
        if self.strike_price:
            _dict['strikePrice'] = self.strike_price.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SodacardsDevpublicV1Product from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "faceValue": SodacardsDevpublicV1ProductFaceValue.from_dict(obj["faceValue"]) if obj.get("faceValue") is not None else None,
            "price": SodacardsDevpublicV1Money.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "strikePrice": SodacardsDevpublicV1Money.from_dict(obj["strikePrice"]) if obj.get("strikePrice") is not None else None,
            "bonus": obj.get("bonus"),
            "minQuantity": obj.get("minQuantity"),
            "maxQuantity": obj.get("maxQuantity"),
            "purchasable": obj.get("purchasable")
        })
        return _obj


